build: trigger

diff --git a/.github/workflows/job.docker-auctions-image.yml b/.github/workflows/job.docker-auctions-image.yml
--- a/.github/workflows/job.docker-auctions-image.yml
+++ b/.github/workflows/job.docker-auctions-image.yml
@@ -25,10 +25,18 @@ jobs:
         id: package-version
         uses: martinbeentjes/npm-get-version-action@v1.3.1
 
+      - name: Print NPM Version
+        run: |
+          echo "NPM current version: '${{ steps.package-version.outputs.current-version }}'"
+          if [ -z "${{ steps.package-version.outputs.current-version }}" ]; then
+            echo "::error::Package version is empty! This will cause tagging issues."
+            exit 1
+          fi
+
       - name: Use Node.js 20.x
         uses: actions/setup-node@v4
         with:
-          node-version: '22.15'
+          node-version: 'lts/*'
           registry-url: 'https://npm.pkg.github.com' # Specify the GitHub Packages registry URL
           scope: '@alexzedim' # Your npm scope
 
